#! /bin/sh

case "$1" in
    start)
        echo "Starting netsim"
        if [ ! -e /var/lib/netsim/status.json ] ; then
          cp /var/lib/netsim/status.json.install /var/lib/netsim/status.json
        fi 
        if [ ! -e /var/lib/netsim/profiles.json ] ; then
          cp /var/lib/netsim/profiles.json.install /var/lib/netsim/profiles.json
        fi 
        /usr/bin/netsim -d
        ;;
    stop)
        echo "Stopping netsim" 
        killall netsim 
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0

